//! Action trait for type-safe state mutations

use std::fmt::Debug;
use std::hash::Hash;

/// Marker trait for actions that can be dispatched to the store
///
/// Actions represent intents to change state. They should be:
/// - Clone: Actions may be logged, replayed, or sent to multiple handlers
/// - Debug: For debugging and logging
/// - Send + 'static: For async dispatch across threads
///
/// Use `#[derive(Action)]` from `tui-dispatch-macros` to auto-implement this trait.
pub trait Action: Clone + Debug + Send + 'static {
    /// Get the action name for logging and filtering
    fn name(&self) -> &'static str;
}

/// Extension trait for actions with category support
///
/// This trait is auto-implemented when using `#[derive(Action)]` with
/// `#[action(infer_categories)]`. It provides methods to query an action's
/// category for routing and filtering.
///
/// # Example
///
/// ```ignore
/// use tui_dispatch::ActionCategory;
///
/// #[derive(Action, Clone, Debug)]
/// #[action(infer_categories)]
/// enum MyAction {
///     SearchStart,
///     SearchClear,
///     ConnectionFormOpen,
/// }
///
/// let action = MyAction::SearchStart;
/// assert_eq!(action.category(), Some("search"));
/// assert!(matches!(action.category_enum(), MyActionCategory::Search));
/// ```
pub trait ActionCategory: Action {
    /// The category enum type generated by the derive macro
    type Category: Copy + Eq + Hash + Debug;

    /// Get the action's category as a string (if categorized)
    fn category(&self) -> Option<&'static str>;

    /// Get the action's category as an enum value
    fn category_enum(&self) -> Self::Category;
}

/// Trait for actions that provide a summary representation for logging
///
/// The default implementation uses the Debug representation. Override
/// `summary()` to provide concise summaries for actions with large payloads
/// (e.g., showing byte counts instead of full data).
///
/// # Example
///
/// ```ignore
/// impl ActionSummary for MyAction {
///     fn summary(&self) -> String {
///         match self {
///             MyAction::DidLoadData { data } => {
///                 format!("DidLoadData {{ bytes: {} }}", data.len())
///             }
///             _ => format!("{:?}", self)
///         }
///     }
/// }
/// ```
pub trait ActionSummary: Action {
    /// Get a summary representation of this action for logging
    ///
    /// Should return a concise string, ideally one line, suitable for
    /// display in a scrolling action log. For actions with large data payloads,
    /// show size/count summaries instead of full content.
    ///
    /// Default implementation uses `Debug` formatting.
    fn summary(&self) -> String {
        format!("{:?}", self)
    }
}
